apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: fe
spec:
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe
        image: destiaeka/todo-app-frontend
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  labels:
    app: be
spec:
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: be
        image: destiaeka/todo-app-backend
        ports:
        - containerPort: 3000


---
kind: Service
apiVersion: v1
metadata:
  name: fe-service
spec:
  selector:
    app: fe
  ports:
  - port: 80
    targetPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: be-service
spec:
  selector:
    app: be
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  labels:
    name: todo-ingress
spec:
  rules:
    - host: ingress.destiaeka.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fe-service
                port:
                  number: 80
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: be-service
                port:
                  number: 3000